sudo: required
services:
  - docker
language: go

go:
  - 1.13.x

git:
  depth: 1

install: true
notifications:
  email: false

before_script:
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $GOPATH/bin v1.25.1
  - docker build -t raunakjodhawat/gorithims:2.1.1 .

script:
  - golangci-lint run       # run a bunch of code checkers/linters in parallel
  - go test -v -race ./... --cover # Run all the tests with the race detector enabled and run all the benchmarks

after_success:
  - echo "$TRAVIS_BRANCH"
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push raunakjodhawat/gorithims:2.1.1
    fi