language: go

go:
  - 1.13.x

git:
  depth: 1

install: true
notifications:
  email: false

before_script:
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $GOPATH/bin v1.25.1
script:
  - golangci-lint run       # run a bunch of code checkers/linters in parallel
  - go test -v -race ./... --cover  # Run all the tests with the race detector enabled